### ISSUE TITLE
Text Editor

### ISSUE THREAD

**Issue by liibin** [os-fpga/FOEDAG#105]
## Motivation
Provides an interface for editing HDL code.

### Code flow
![image](https://user-images.githubusercontent.com/91514334/143966383-bbf88f0d-3447-489f-a08f-c039e10151ef.png)

### Basic functions

- HDL syntax highlight and error indicator
- Multi-tab to open multiple files
- Basic editing operations,such as cut,copy,paste,delete,undo,redo.

I will use a third-party open source library: QScintilla。
https://www.riverbankcomputing.com/static/Docs/QScintilla/

Open to discussion here.

**Comment by alaindargelas** [comment]
Must have feature: 
  - Search across entire project RTL source code
     - Find all module instances of a module definition
     - find all occurrence of a text 
  - Link to/from hierarchy tree viewer
Nice to have features: Auto-completion (Might require language server)

**Comment by liibin** [comment]
> Must have feature:
> 
> * Search across entire project RTL source code
>   
>   * Find all module instances of a module definition
>   * find all occurrence of a text
> * Link to/from hierarchy tree viewer
> 
> Nice to have features: Auto-completion (Might require language server)

OK，I'll add this feature.
