### ISSUE TITLE
./dbuild/bin/newproject --replay tests/TestGui/gui_new_project.tcl does not advance the menus anymore (Used to work)

### ISSUE THREAD

**Issue by alain-rs** [os-fpga/FOEDAG#112]
> **Describe the bug**
> A clear and concise description of what the bug is.

> **To Reproduce**
> Steps to reproduce the behavior:
> 1. Clone repository and checkout commit id: <The problem commit id>
> 2. Execute a test case or your own example: <more details>
> 3. See error

> **Expected behavior**
> A clear and concise description of what you expected to happen.

> **Screenshots**
> If applicable, add screenshots to help explain your problem.

> **Enviornment (please complete the following information):**

>  - OS: 

>  - Compiler:

> - Version:

> **Additional context**
> Add any other context about the problem here.

**Comment by liibin** [comment]
During CI, macos-clang is often stuck in unit tests.  But it's successful to execute the test command alone.
