### ISSUE TITLE
Top level window

### ISSUE THREAD

**Issue by alain-rs** [os-fpga/FOEDAG#136]
Add a top-level window with panes, tabs, to the FOEDAG main executable with initially the project viewer, Text Editor, Console

**Comment by alain-rs** [comment]
- Bring QML dependancies into the cmake
- Change the main.cpp (Foedag::initGui) to use the QML+Tcl event loop instead of just QT+Tcl

**Comment by ravic-rs** [comment]
This is complete, closing.
