### ISSUE TITLE
batch command: Tcl Error: extra characters after close-quote

### ISSUE THREAD

**Issue by KochynVolodymyr** [os-fpga/FOEDAG#149]
I got random problem with batch command.
E.g. batch {synth}

gives output:

batch {synth}
true
Running batch...
Tcl Error: extra characters after close-quote
Batch Done.

Looks like smth uninitialized because it cause randomly.

**Comment by alain-rs** [comment]
Fixed by #152 

You can try in the console:
batch { synth ; globp }
