### ISSUE TITLE
Tcl test action success when one of the command execution failed.

### ISSUE THREAD

**Issue by KochynVolodymyr** [os-fpga/FOEDAG#161]
Check this actions:
https://github.com/KochynVolodymyr/FOEDAG/runs/5057035101?check_suite_focus=true

**One of the test fail:**
`CONSOLE GUI: source command`

`    while executing`
`"console_proc process_qt_events"`
`    ("after" script)`

But action pass successfully.

**Expected result:** Action test should fail.

_**return TCL_ERROR**_ should cause test fail. But it doesn't.

**Comment by alain-rs** [comment]
Fixed by #164
