### ISSUE TITLE
Tcl interpreter doesn't wait until Qt code finish all operations. As the result - there is no guaranty tests pass succesfully.

### ISSUE THREAD

**Issue by KochynVolodymyr** [os-fpga/FOEDAG#174]
Currently one of the test - console_multiline - didn't finish successfully. Look at the log:

TEST_LOOP_ENTERED
CONSOLE GUI: pwd command
SUCCESS
CONSOLE GUI: source command
SUCCESS
CONSOLE GUI: multiline
CONSOLE GUI: cancelation
SUCCESS
GUI EXIT

there is no **SUCCESS** keyword after running test. Tcl didn't wait and can't check status from Qt. 
This test should fail but it still pass.

Need to apply general solution and not only fix for the console.

**Possible solution:**
Tcl waits for some event from Qt for ending. If there is no such event, fail test after some timeout.

**Comment by alain-rs** [comment]
Moreover, that test creates a memory corruption:

TEST_LOOP_ENTERED
CONSOLE GUI: console_pwd
SUCCESS
CONSOLE GUI: console_proc
SUCCESS
CONSOLE GUI: console_multiline
TclStackFree: incorrect freePtr (0x561bb9fbadb0 != 0x561bb9fbae90). Call out of sequence?
Illegal instruction (core dumped)
make: *** [Makefile:133: test/gui] Error 132
