### ISSUE TITLE
Incremental Build Support for Third Party Libraries

### ISSUE THREAD

**Issue by tangxifan** [os-fpga/FOEDAG#19]
**Is your feature request related to a problem? Please describe.**

This is an issue detected in pull request #18 
Because the third party libraries, i.e., Tcl and Zlib, do not have native CMake scripts. So we use CMake to hook their Makefile.
As a result, the build for Tcl is not completely incremental, the configure part is redone for every compilation. 
This will cause a long runtime each time we want to rebuild the source codes (nothing cached for these libraries)

**Describe the solution you'd like**
The solution is to find a way in CMakelist.txt for these third part libraries.
When creating a custom target in CMake, see if it can identify dependencies and avoid rebuilding from scratch

**Comment by alain-rs** [comment]
Fixed by #26
