### ISSUE TITLE
[Console] Wordwrap breakes the command.

### ISSUE THREAD

**Issue by KochynVolodymyr** [os-fpga/FOEDAG#211]
Type some long command and make window smaller in order to break command by word wrap. Press Enter.
Results: console run wrong command. It took last part of the command.

**Comment by KochynVolodymyr** [comment]
We don't have word wrap in the console anymore. This could be closed

**Comment by ravic-rs** [comment]
@KochynVolodymyr please add some information or references to why we don't have it anymore and close it.

**Comment by KochynVolodymyr** [comment]
https://github.com/os-fpga/FOEDAG/blob/8ee7964b6b9815b93684481a58d5d6c658c512b0/src/Console/TclConsoleWidget.cpp#L48
