### ISSUE TITLE
New project wizard features

### ISSUE THREAD

**Issue by alain-rs** [os-fpga/FOEDAG#237]
- Be able to change the order of source file
- Be able to remove source file
- From the Project Viewer, be able to re-open the project wizard of an existing project and edit any fields from the wizard.
- Create the project in the local directory from where the tool was launched, or give a directory finder choice, not in $HOME

**Comment by liibin** [comment]
> * Be able to change the order of source file
> * Be able to remove source file

It has been realized through these three buttons.   I'll change the word delete to remove.
<img width="606" alt="6468746331166" src="https://user-images.githubusercontent.com/91514334/157567207-09e90626-a34e-47e2-945d-9320208c65e1.png">

**Comment by alain-rs** [comment]
Thanks!
This feature is still missing:
From the Project Viewer, be able to re-open the project wizard of an existing project and edit any fields from the wizard.

When clicking in the Project Viewer instead of having the "Add files" open just the Wizard at the "add file" view, open the entire wizard and allow to click "Finish" on the current view.

In the Project Viewer, the "create design" menu does not seem to work, the "design" panel should open to show the created design.

In the Project Viewer, there is no "Add Constraints" menu, it points to the "Add files" menu, open the wizard to the constraint view in the wizard.

**Comment by alain-rs** [comment]
@liibin, let me know if you are going to work on these items, we need to get the project definition working well very soon.
Please try different scenarios (Testing).

**Comment by liibin** [comment]
> @liibin, let me know if you are going to work on these items, we need to get the project definition working well very soon. Please try different scenarios (Testing).

I'm busy with the company's annual reports.I am going to work on these items next week.

**Comment by ravic-rs** [comment]
Closing this as the feature update branch has been merged.
