### ISSUE TITLE
Example design

### ISSUE THREAD

**Issue by alain-rs** [os-fpga/FOEDAG#252]
- Right click on Open file on led.v after opening the sample project does not open the file in the browser. 
- "make" should install the examples in the build library (see example below).
-  
- "make install" should install the examples directory under /usr/local/share/foedag/examples (Check how device.xml is now installed under /usr/local/share/foedag/etc/device.xml)

**Comment by liibin** [comment]
> * Right click on Open file on led.v after opening the sample project does not open the file in the browser.

I didn't find this problem.
