### ISSUE TITLE
Stop button needs to stop any task

### ISSUE THREAD

**Issue by alain-rs** [os-fpga/FOEDAG#262]
The new CompilerOpenFPGA::Synthesize method runs yosys as a separate process.
Need to kill the process or close the pipe (Which should kill the process) when the stop command is pressed.

**Comment by alain-rs** [comment]
Run 
./build/bin/raptor --compiler openfpga --script tests/Testcases/raygentop/raygentop.tcl

Stop the process using the stop button. 
There is an error message from QT

**Comment by KochynVolodymyr** [comment]
@alain-rs is this issue solved?

**Comment by alain-rs** [comment]
Yes.

**Comment by nadeemyaseen-rs** [comment]
@alain-rs  I have tested it today with `FOEDAG/tests/Testcases/aes_decrypt_fpga/aes_decrypt.tcl`, the process did not stop on pressing the stop button in raptor.

**Comment by KochynVolodymyr** [comment]
Stop button never work in case --script.

**Comment by alaindargelas** [comment]
@KochynVolodymyr the stop button should work for all the commands "synth, pack, place, route..." regardless if they where typed manually or running through a script.
