### ISSUE TITLE
Tcl error messages are silent

### ISSUE THREAD

**Issue by alain-rs** [os-fpga/FOEDAG#297]
Edit  tests/Testcases/raygentop/raygentop.tcl, add an illegal command at the beginning of the file,
no error show, simply the prompt
This has to do with the latest project sync, that was working before.
I could show error in a command using the ErrorMessage method, but if the error is an illegal script the Tcl error messaging has been suppresed

./build/bin/foedag --script  tests/Testcases/raygentop/raygentop.tcl --batch

**Comment by KochynVolodymyr** [comment]
I tried version month old and before my changes. Looks like it haven't work at all. It doesn't related to sync.
If you have version that works please put here.

**Comment by KochynVolodymyr** [comment]
Caused by https://github.com/os-fpga/FOEDAG/pull/293
