### ISSUE TITLE
All error messages originating from a Tcl script (--script <file>) need to show the Tcl error stack

### ISSUE THREAD

**Issue by alain-rs** [os-fpga/FOEDAG#299]
No error stack is showing currently, again some masking issue.
Users have to type puts $errorInfo to see the errors...

**Comment by KochynVolodymyr** [comment]
How I can reproduce this. Please put any command. When this works fine.

**Comment by alain-rs** [comment]
Create a file:
```
proc a { } {
  b
}
proc b { } {
 not_defined
}
a
```

tchsh shows the full stack trace:

~/FOEDAG$ tclsh t.tcl
invalid command name "not_defined"
    while executing
"not_defined"
    (procedure "b" line 2)
    invoked from within
"b"
    (procedure "a" line 2)
    invoked from within
"a"
    (file "t.tcl" line 7)

FOEDAG only shows the final error. It has to do with $errorInfo not being displayed.

~/FOEDAG$ ./dbuild/bin/foedag --compiler openfpga --script t.tcl --batch
Tcl only mode
invalid command name "not_defined"
%

**Comment by KochynVolodymyr** [comment]
Got it! I saw this only in replay mode, we force to output this.  But not in other cases.

**Comment by alaindargelas** [comment]
Note that in GUI mode, we want to recognize (file "t.tcl" line 7) as a file location and create an hyperlink to the tcl file

**Comment by KochynVolodymyr** [comment]
![image](https://user-images.githubusercontent.com/95262932/163794463-cdbde264-764a-4508-9f82-5803b710b6ff.png)

![image](https://user-images.githubusercontent.com/95262932/163794631-2c9fe3bf-c5fc-48cb-bf66-12449757590a.png)
