### ISSUE TITLE
stderr shows in the terminal while GUI mode

### ISSUE THREAD

**Issue by alain-rs** [os-fpga/FOEDAG#302]
It should show in the GUI console instead (in red).

alain@alain-xps:~/FOEDAG$ ./dbuild/bin/foedag --compiler openfpga --script tests/Testcases/raygentop/raygentop.tcl 
% Error 1: 
Type: Routing
File: /home/alain/RapidSilicon/Raptor/OpenFPGA_RS/vpr/src/base/vpr_api.cpp
Line: 801
Message: Fixed channel width must be specified when loading routing (was -1)
Error 1: 
Type: Routing
File: /home/alain/RapidSilicon/Raptor/OpenFPGA_RS/vpr/src/base/vpr_api.cpp
Line: 801
Message: Fixed channel width must be specified when loading routing (was -1)
done!
QObject::~QObject: Timers cannot be stopped from another thread
Segmentation fault (core dumped)

**Comment by KochynVolodymyr** [comment]
It works for me

**Comment by alaindargelas** [comment]
Yes, but the errors show in the terminal.
Have you setup the whole compiler flow? Yosys + VPR? You need to do that to be able to test things properly from there on.

**Comment by alaindargelas** [comment]
The messages above are error messages from VPR.
If you don't have VPR you cannot test properly.

**Comment by KochynVolodymyr** [comment]
got it! I didn't setup VPR

**Comment by KochynVolodymyr** [comment]
![image](https://user-images.githubusercontent.com/95262932/163821172-97015fe4-80d1-43bd-9c4f-06728b6978c1.png)
