### ISSUE TITLE
Faulty external doc link to yosys_doc

### ISSUE THREAD

**Issue by Exouxas** [os-fpga/FOEDAG#318]
> **Describe the bug**
> Using the link in the FOEDAG docs page to go to the yosys docs redirects you to a page which promotes gambling sites.

Which part of FOEDAG is buggy
- [x] Documentation 
- [ ] Libraries
- [ ] Plug-ins
- [ ] Engine
- [ ] Tests

> **To Reproduce**
> Steps to reproduce the behavior:
> 1. Navigate to https://foedag.readthedocs.io/en/latest/
> 2. Press the link to yosys_doc
> 3. Takes you to http://www.clifford.at/yosys/ which redirects to https://clifford.at/

> **Expected behavior**
> I expected it to take me to some correct documentation site.  https://yosyshq.net/yosys/documentation.html would be a good option.

> **Screenshots**
> If applicable, add screenshots to help explain your problem.
![Gamble site](https://user-images.githubusercontent.com/26272249/165630247-483bc9ea-182b-4888-a539-3343f8e9913d.png)

> **Enviornment (please complete the following information):**
> - Version:
- [x] Current master
- [ ] Others. If so, please specify Github commit id:

> **Additional context**
> Seems like the documentation page has been migrated some time after October 28, 2021 according to archive.org

**Comment by alain-rs** [comment]
Fixed by #320
