### ISSUE TITLE
Stop button functionality

### ISSUE THREAD

**Issue by KochynVolodymyr** [os-fpga/FOEDAG#328]
The Stop button should only be operative for the commands:

ipgenerate
synth
pack
globp
place
route
sta
power
bitstream

Applied to single command, script mode or Start button.

**Comment by alain-rs** [comment]
The stop button stops the script which is good, but it does not kill the underlying process immediately, it should send a signal kill (at least on Linux and MacOS) to the underlying process (yosys, vpr....)

**Comment by KochynVolodymyr** [comment]
This issue could be closed.
