### ISSUE TITLE
Cannot create children for a parent that is in a different thread.

### ISSUE THREAD

**Issue by alain-rs** [os-fpga/FOEDAG#341]
./build/bin/foedag

Simply click on Synthesize button, the following error shows in the terminal:

QObject: Cannot create children for a parent that is in a different thread.
(Parent is FOEDAG::Project(0x56315c6e2960), parent's thread is QThread(0x56315ee64120), current thread is QThread(0x56315fbdac60)
QBasicTimer::start: QBasicTimer can only be used with threads started with QThread

**Comment by KochynVolodymyr** [comment]
The problem appears here: void Project::InitProject
when create design call.
Need to check after #260 will be closed.
