### ISSUE TITLE
Hyperlink not pointing to the line

### ISSUE THREAD

**Issue by alain-rs** [os-fpga/FOEDAG#344]
When stopping Synthesis, the hyperlink below points to the file, but not to the line

ERROR: eval canceled
    while executing
"synthesize delay"
    (file "[tests/Testcases/aes_decrypt_fpga/aes_decrypt.tcl](https://github.com/home/alain/RapidSilicon/Raptor/tests/Testcases/aes_decrypt_fpga/aes_decrypt.tcl)" line 6)

**Comment by KochynVolodymyr** [comment]
How it should point to line? What you expect? how it should display that?

**Comment by KochynVolodymyr** [comment]
![image](https://user-images.githubusercontent.com/95262932/166915218-c1a09bd0-7f16-4bd1-9dd9-ee915fb3298c.png)

Functionality added. The icon can be changed to any.
