### ISSUE TITLE
FOEDAG consumes 100% CPU when Yosys or VPR is running

### ISSUE THREAD

**Issue by alain-rs** [os-fpga/FOEDAG#353]
The sub process uses 100% of a core, but Foedag uses 100% of a second core, it should only use a few percents or 10%.

**Comment by KochynVolodymyr** [comment]
Looks good when run in batch mode. Perhaps something with threads management.

**Comment by KochynVolodymyr** [comment]
Problem with WorkerThread::waitForFinish

**Comment by KochynVolodymyr** [comment]
Command Stop in batch mode also doesn't work. Need to rework approach with thread.
Steps:
* Run ./build/bin/foedag --batch
* synth
* stop

**Comment by alaindargelas** [comment]
Yes, that used to work for the dummy compiler class, and I believe now it does not work for that anymore.
That is not super important that it works in batch mode. (Not high priority).
