### ISSUE TITLE
GUI freeze when resized while running a task

### ISSUE THREAD

**Issue by alain-rs** [os-fpga/FOEDAG#362]
While running a long Sythesis, or Place or Route task, if the user resizes the top level window or one of the widget separators, the GUI freezes until the task is completed.

**Comment by KochynVolodymyr** [comment]
Can't reproduce, works good to me.

**Comment by alain-rs** [comment]
Use Raptor on the large design Testcases/aes_decrypt_gate/aes_decrypt_gate.tcl and resize many times, eventually it freezes
