### ISSUE TITLE
Close file icon color

### ISSUE THREAD

**Issue by alain-rs** [os-fpga/FOEDAG#393]
The Close file icon in the text editor is red, we should reserve the color red for real issues reported by the tool, closing a file should have a grey-ish x icon.

**Comment by KochynVolodymyr** [comment]
This is standard Qt control with standard icon. In order to change it need some workaround. Both available approaches have some problems.

**Comment by alaindargelas** [comment]
QT look and feel needs an uplift for sure. Not high priority but some work on the look and feel is required.
