### ISSUE TITLE
Regarding windows build of FOEDAG.

### ISSUE THREAD

**Issue by someshwar-ms** [os-fpga/FOEDAG#418]
Is the Windows build of FOEDAG possible today? If so are there any build instructions for the same.
Are both MSVC and MSYS2 GCC compiler support available?

**Comment by alain-rs** [comment]
Yes, Yes and Yes.
All the instructions are in the CI: 
https://github.com/os-fpga/FOEDAG/blob/a33996b3bec361769f89cd686b4422c54eec5a62/.github/workflows/main.yml#L319
