### ISSUE TITLE
Add a new Test for Compilation without Qt to CI

### ISSUE THREAD

**Issue by tangxifan** [os-fpga/FOEDAG#45]
**Is your feature request related to a problem? Please describe.**
As the core of the IDE is Tcl+GUI,  in all the tests deployed in CI, the Qt compilation is always enabeld.
However, we should also have a test to validate compilation without Qt, where only Tcl will run.

**Describe the solution you'd like**
- In CMakelist, make Qt package optional
- If source codes, use ``#WITH_GUI`` to skip Qt in compilation

Feel free to comment

**Comment by alain-rs** [comment]
Done
