### ISSUE TITLE
New Project menu pick is disabled after finishing project creation

### ISSUE THREAD

**Issue by skyler-rs** [os-fpga/FOEDAG#464]
> **Describe the bug**
> After finishing the new project wizard, the "New Project" menu pick is disabled until app restart.

> **To Reproduce**
> Steps to reproduce the behavior:
> 1. Click File > New Project
> 2. Click through the creation steps and click finish
> 3. Click File
> 4. Note that "New Project" is no longer selectable
![image](https://user-images.githubusercontent.com/103447061/174119565-ec4706e9-4e27-4281-89f4-44fc2304b393.png)

> **Expected behavior**
> The menu pick shouldn't be disabled and the user should be able to re-run the New Project wizard, creating and loading the new project. (Note, just from observing it's state when opening/closing it mid use, it looks like this might be one dialog instance so re-running the project wizard might take some refactoring.

**Comment by skyler-rs** [comment]
Initial gui task for Zaryab once he starts working in the code

**Comment by skyler-rs** [comment]
Note: This might be a dupe of https://github.com/os-fpga/FOEDAG/issues/218

**Comment by KochynVolodymyr** [comment]
This is actually done. After project being closed - new project become available.

**Comment by KochynVolodymyr** [comment]
I guess so

**Comment by skyler-rs** [comment]
Gotcha, i'll close this for now as I'm not sure the additional logic would really add much usability-wise and probably isn't a good starting task for Zaryab.
