### ISSUE TITLE
Menu Picks That Invoke a Dialog Require "..." in their text

### ISSUE THREAD

**Issue by skyler-rs** [os-fpga/FOEDAG#465]
> **Describe the bug**
> UI standards call for all menu picks that require additional user input to have ... at the end of their text

> **To Reproduce**
> Click File Menu
> Observe that New, Open File, New Project, Open Project all invoke dialogs but are missing "..."
![image](https://user-images.githubusercontent.com/103447061/174123041-a30cdf4c-71ae-40fd-9a03-cbffdeef2e78.png)

> **Expected behavior**
> Change menu picks to "New...", "Open File...", "New Project...", "Open Project..."

**Comment by skyler-rs** [comment]
Initial gui task for Zaryab once he starts working in the code

**Comment by zaryabkhan-rs** [comment]
The above bug is fixed. Do I also need to fix this part as well ?
![casds](https://user-images.githubusercontent.com/109368108/179926434-96e2e97f-cfc8-4300-928c-5f3725b3e47d.png)

**Comment by skyler-rs** [comment]
Good catch, "Create Constraints Sets", "Create Simulation Set", and "Add Sources" should be changed eventually, this issue is named generically enough that you could make those changes as well if you want or we can create a new issue for them and resolve them later.

**Comment by zaryabkhan-rs** [comment]
Yeah sure, I will make changes to these mentioned options in this existing issue. No need to create new one.

**Comment by ravic-rs** [comment]
> 
Any reference to the UI standards?

**Comment by skyler-rs** [comment]
Hey @ravic-rs , I'm not sure about a specific standard, but it was at least a [commonly accepted practice in desktop guis](https://en.wikipedia.org/wiki/Ellipsis#Usage_in_computer_system_menus). It might be losing it's footing as a standard as mobile devices take over and there is less space for the ... however.

**Comment by ravic-rs** [comment]
> Hey @ravic-rs , I'm not sure about a specific standard, but it was at least a [commonly accepted practice in desktop guis](https://en.wikipedia.org/wiki/Ellipsis#Usage_in_computer_system_menus). It might be losing it's footing as a standard as mobile devices take over and there is less space for the ... however.

Thanks! Here's a one such reference. 
https://docs.microsoft.com/en-us/windows/win32/uxguide/cmd-menus#using-ellipses
