### ISSUE TITLE
Fix Typos in New Project Wizard

### ISSUE THREAD

**Issue by skyler-rs** [os-fpga/FOEDAG#467]
> **Describe the bug**
> There are a number of formatting issues in the New Project Wizard

> **Expected behavior**
> Capitalize Next Button
> Add a space after each comma for the following parts:
- "Next,you will specify..."
- "Finally,you will specify..."
- "You will be able to add sources,create block designs in IP integrator,generate IP, run RTL analysis,synthesis,implementation,design planning and analysis."
- Improve any other formatting/wording issues you might find.

**Comment by zaryabkhan-rs** [comment]
This issue has been fixed.
