### ISSUE TITLE
UI glitch in tasks table view

### ISSUE THREAD

**Issue by TarasSydor** [os-fpga/FOEDAG#518]
In tasks view, expanding/collapsing 'Packing' and 'Global Placement' tasks happens immediately, but collapse icon gets updated with some delay.

Also, the view may get distorted (rows overlap) as on the screenshot below:
![Screenshot from 2022-07-13 18-49-07](https://user-images.githubusercontent.com/109239890/179017897-d2622fee-0cd9-4c0d-8c6e-70f89ee45416.png)

Steps to reproduce aren't clear: several collapse\expand actions in a row causes visual side effects.

**Comment by alain-rs** [comment]
@TarasSydor, you are added to the list of contributors. You can self-assign now.
