### ISSUE TITLE
Show the full path of files read by the project 

### ISSUE THREAD

**Issue by TarasSydor** [os-fpga/FOEDAG#537]
The request originally comes from Avinash.

Currently we only see the file name in highlighted area:
![зображення](https://user-images.githubusercontent.com/109239890/179780945-303d6528-e743-4f7f-8362-9d877b694ecb.png)

Can we show entire path?

The full path is available in files properties panel. Showing complete path in a tab will consume most (if not all) available space and break usability. 
As a solution we (Ravi, Volodymyr, Taras) agreed on showing a tooltip with full path when hovering over the tab. 

As a future improvement we may want to show only part of path (up to 3 branches) or truncate it if width takes more than n pixels.

**Comment by skyler-rs** [comment]
Did a bit of testing w/ this feature earlier in the week and I think tooltips can be added with the following line being added to text_editor_form.cpp::TextEditorForm::OpenFile():
`m_tab_editor->setTabToolTip(index, fileInfo.absoluteFilePath());`
