### ISSUE TITLE
Make litex ip generator recursively search directories

### ISSUE THREAD

**Issue by alain-rs** [os-fpga/FOEDAG#548]
Make this code recursively search sub-directories:
https://github.com/os-fpga/FOEDAG/blob/dcbb36de7593c0ca8aa62c28cfa4ed9af9aaabc5/src/IPGenerate/IPCatalogBuilder.cpp#L81

**Comment by alain-rs** [comment]
@zaryabkhan-rs, what is the status of this?

**Comment by zaryabkhan-rs** [comment]
> @zaryabkhan-rs, what is the status of this?

Yeah I was working on pin assignment issue, which is done now. I need some requirements for this issue so that I can start working on it.

**Comment by zaryabkhan-rs** [comment]
And What's the current working action for this issue to get an idea?

**Comment by ravic-rs** [comment]
Assigned to Skyler as part of the ip config project.

**Comment by ravic-rs** [comment]
Completed with https://github.com/os-fpga/FOEDAG/pull/607
