### ISSUE TITLE
Use INSTALL.md in the front-page

### ISSUE THREAD

**Issue by tangxifan** [os-fpga/FOEDAG#55]
> **Describe the bug**
> A clear and concise description of what the bug is.

Which part of FOEDAG is buggy
- [x] Documentation

A problem seen in #54 

> **To Reproduce**
> Steps to reproduce the behavior:
> 1. You can see that in the README.md, the installation guidelines are hard-coded and it is out-of-data as compared to latest version in INSTALL.md. We should use ``include`` to avoid out-of-date guidelines. I have already done so in the sphinx documentation: https://foedag.readthedocs.io/en/latest/tutorials/getting_started/build_instructions/#clone-and-initialize-submodules

> **Expected behavior**
We should always use the INSTALL.md as the golden reference. Anywhere else, we should link to the INSTALL.md rather than create a hard copy.

> **Screenshots**
Currently front page:

![image](https://user-images.githubusercontent.com/11499826/138752854-e503b296-e938-4322-b986-02b9c86883f5.png)

> **Enviornment (please complete the following information):**

>  - OS: 

>  - Compiler:

> - Version:

> **Additional context**
> Add any other context about the problem here.

**Comment by alain-rs** [comment]
This is fixed
