### ISSUE TITLE
While manually resizing Task column in task view, button doesn't keep up

### ISSUE THREAD

**Issue by TarasSydor** [os-fpga/FOEDAG#555]
> **Describe the bug**
By default, all the columns are sized according to their content.
Task column allows manual resizing. While holding the mouse, text gets truncated according to the current width, but the
button remains stable till the user releases the button:

![image](https://user-images.githubusercontent.com/109239890/182206046-22fbcee0-8832-43bc-bcde-23872e5b67ee.png)

Status column doesn't have this problem because it has fixed width. Stats can also be resized, but doesn't have such button.
So it's just Task column.

**Comment by TarasSydor** [comment]
The main question here: should we allow to shrink the Task columns so that text doesn't fit?
The issue is present regardless of the answer, as enlarging the column has the same effect - button remains stable till releasing the mouse. 
So unless we disable Task column resizing at all, the layout problem has to be fixed.

**Comment by ravic-rs** [comment]
@TarasSydor you had made some progress on this issue a week or so ago. Is it ready for a PR ?

**Comment by ravic-rs** [comment]
@KochynVolodymyr does your PR https://github.com/os-fpga/FOEDAG/pull/604/files affect this one ?

**Comment by KochynVolodymyr** [comment]
> @KochynVolodymyr does your PR https://github.com/os-fpga/FOEDAG/pull/604/files affect this one ?

No, it isn't

**Comment by ravikiranchollangi** [comment]
Closing this as we updated the widget now.
