### ISSUE TITLE
No project file when run in batch mode

### ISSUE THREAD

**Issue by KochynVolodymyr** [os-fpga/FOEDAG#556]
**Describe the bug**
When run some script in a batch mode - no project file is created.

**To Reproduce**
1. Run command: foedag --batch --script tests/Testcases/trivial/test.tcl

**Expected behavior**
Project folder is created and file test.ospr is created inside.

**Comment by zaryabkhan-rs** [comment]
For this issue, the whole architecture of adding files would  be implemented for batch command just like we have for GUI to add files from new project dialog.
