### ISSUE TITLE
Add Directory... doesn't work correctly

### ISSUE THREAD

**Issue by KochynVolodymyr** [os-fpga/FOEDAG#558]
**Describe the bug**
If use Add Directory... for source file synthesize will fail.

**To Reproduce**
1. Start new project.
2. Try to add source using Add directory...  button
3. Press  Start button

**Actual behavior**
Synth failed because of wrong path to files.

**Expected behavior**
Build pass successfully.

**Additional context**
If open yosis file - there are missing all files, just path to the folder

**Comment by ravic-rs** [comment]
Closing, it's completed.
