### ISSUE TITLE
Add Windows build documentation

### ISSUE THREAD

**Issue by ravic-rs** [os-fpga/FOEDAG#597]
**Is your feature request related to a problem? Please describe.**
Documentation update due to https://github.com/os-fpga/FOEDAG/pull/589

**Describe the solution you'd like**
Update doc files as needed to help user to install foedag under Windows OS.

**Describe alternatives you've considered**
NA

**Additional context**

**Comment by coolbreeze413** [comment]
@ravic-rs : I have added a PR with the doc update.
This updates the existing doc with the dependencies setup using the MSYS2 env.
As build/install steps would remain the same as default (`make` or `make release` etc.) I have not modified any other documents.
Please let me know if it looks ok.

**Comment by ravic-rs** [comment]
> @ravic-rs : I have added a PR with the doc update. This updates the existing doc with the dependencies setup using the MSYS2 env. As build/install steps would remain the same as default (`make` or `make release` etc.) I have not modified any other documents. Please let me know if it looks ok.

Thank you, looks good. We will try those steps later and get back if more details are needed.
