### ISSUE TITLE
Once project is created, it cannot be changed

### ISSUE THREAD

**Issue by alain-rs** [os-fpga/FOEDAG#640]
If you add the wrong constraint file while creating a project in the GUI, it cannot be removed. Worse, the widget that is supposed to show how to edit the constraint specification does not show the original constraint file
![Screenshot from 2022-09-09 13-29-58](https://user-images.githubusercontent.com/90641725/189437991-5f7b15fe-0a76-41c6-94c9-45bc47252734.png)

**Comment by alain-rs** [comment]
@ravic-rs, please make sure that all the project settings can be edited, files, device target... once the project is created and re-opened for edits.

**Comment by KochynVolodymyr** [comment]
This widget just show new files but not the old. This is how it designed. But of you want change order in your design - no chance. There is bug with remove.

**Comment by KochynVolodymyr** [comment]
No chance to change target device

**Comment by alaindargelas** [comment]
We need everything to be editable.

**Comment by ravic-rs** [comment]
We will take a look.

**Comment by KochynVolodymyr** [comment]
@alain-rs 1. User are able to remove file via context menu. 2. This window is only for adding or creating new files. Like in vivado.

**Comment by alain-rs** [comment]
Closing this issue, wizard issues are tracked with an internal Jira.
