### ISSUE TITLE
Use CMake as the building system for this project

### ISSUE THREAD

**Issue by tangxifan** [os-fpga/FOEDAG#7]
@MidsummerNight I had a discussion with  @alain-rs 

He suggest to use the [CMake](https://cmake.org/) to build our Qt project, rather than the [qmake](https://doc.qt.io/qt-5/qmake-manual.html). What is your take on this?

**Comment by alaindargelas** [comment]
Just to put some light into this.
qmake, the native QT make system was ahead of its time 20 years ago. But cmake and other build systems came along and qmake is now a relic of the past.
Most github projects use cmake and it is trivial to import hierarchically submodules while using it.
qmake would make it cumbersome to mix and match subsystems.

**Comment by alain-rs** [comment]
Done
