### ISSUE TITLE
Please update the following actions to use Node.js 16: styfle/cancel-workflow-action</div>

### ISSUE THREAD

**Issue by alain-rs** [os-fpga/FOEDAG#767]
Workflows need updating.

<div class="mt-1 mb-3 px-3">
          <div class="mx-0 mx-md-1">
            <h4 class="text-bold">Annotations</h4>
            <div class="color-fg-muted text-small">5 warnings</div>
          </div>
        </div>
        

 
--

                      <a class="d-block no-underline Link--secondary color-fg-default" href="https://github.com/os-fpga/FOEDAG/actions/runs/3349337132/jobs/5549238619">
                          <strong>valgrind</strong>
                        
                      </a>
                      <div class="color-fg-muted">
                        <div data-target="annotation-message.annotationContainer" class="text-small text-mono annotation--expanded">
                          <div>Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: styfle/cancel-workflow-action</div>
                        </div></div>

**Comment by ravic-rs** [comment]
It's complete.
