### ISSUE TITLE
I compiled and installed FOEDAG on windows, but run failed

### ISSUE THREAD

**Issue by liibin** [os-fpga/FOEDAG#78]
The IDE I use is QT creator. MSVC2019 compilation environment
I compiled and installed FOEDAG on windows, but run failed

![image](https://user-images.githubusercontent.com/91514334/140015613-55eb226c-befb-4ee3-8d8b-125467784e1e.png)

Unable to locate program input point...
I only compile and execute foedag.exe, which has the same problem.
What should I do?

**Comment by alain-rs** [comment]
Can you "make test" to run the batch mode tests?

**Comment by alaindargelas** [comment]
Note: when we create ship-able binaries, that has to be solved using a .bat wrapper that sets the path automatically prior to invoke the executable (or other similar means).
