### ISSUE TITLE
Main branch msvc starts failing with no code change

### ISSUE THREAD

**Issue by alaindargelas** [os-fpga/FOEDAG#80]
> **Describe the bug**
> A clear and concise description of what the bug is.

> **To Reproduce**
Simply rerun one of the runs from main that used to pass, and observe the msvc failure, something about a .vc file syntax and multiple processes accessing a file. 
Looks like something changed in the compilation environment.

> **Expected behavior**
> A clear and concise description of what you expected to happen.

> **Screenshots**
> If applicable, add screenshots to help explain your problem.

> **Enviornment (please complete the following information):**

>  - OS: 

>  - Compiler:

> - Version:

> **Additional context**
> Add any other context about the problem here.

**Comment by alain-rs** [comment]
@liibin do you see this problem when you compile locally on Windows? Or is it just a github issue?

**Comment by tangxifan** [comment]
@alain-rs I experienced some changes on Github runner machines without any notification from Github. This time it may be the same. Last time, I just wait for 2 weeks, the problem was resolved (Github did something under table).

**Comment by liibin** [comment]
> @liibin do you see this problem when you compile locally on Windows? Or is it just a github issue?

I encountered an out of memory error. After I close other apps, the compilation is successful and can run.

**Comment by alaindargelas** [comment]
Thanks, so it is a change in github environment.
We are going to set our own runner actions for Windows on our servers as soon as possible.

**Comment by alain-rs** [comment]
The latest version of cmake used by github has a bug, 
if I fix the version of cmake to the previous version, msvc runner works again....

**Comment by alain-rs** [comment]
Fixed by #79
